databases:
  - name: devBLog
    databaseName: devBLog
    user: devBLog
    region: singapore

services:
  - type: web
    name: devBLog
    region: singapore
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: devBLog
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
