databases:
  - name: devblog
    databaseName: devblog
    user: devblog
    region: singapore

services:
  - type: web
    name: devblog
    region: singapore
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn devblog.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: devblog
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
